//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryBot.lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KryBot.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт не активирван.
        /// </summary>
        internal static string AccountNotActive {
            get {
                return ResourceManager.GetString("AccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Библиотека .
        /// </summary>
        internal static string DllNotLoad {
            get {
                return ResourceManager.GetString("DllNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не была загружена. .
        /// </summary>
        internal static string DllNotLoad_1 {
            get {
                return ResourceManager.GetString("DllNotLoad_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершено.
        /// </summary>
        internal static string DoFarm_Finish {
            get {
                return ResourceManager.GetString("DoFarm_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт....
        /// </summary>
        internal static string DoFarm_Start {
            get {
                return ResourceManager.GetString("DoFarm_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация.
        /// </summary>
        internal static string GetBotInConfig_Config {
            get {
                return ResourceManager.GetString("GetBotInConfig_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не загружена. Файл не существует или сломан..
        /// </summary>
        internal static string GetBotInConfig_NotLoaded {
            get {
                return ResourceManager.GetString("GetBotInConfig_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на угля.
        /// </summary>
        internal static string GiveawayJoined_Coal {
            get {
                return ResourceManager.GetString("GiveawayJoined_Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на подтверждено за.
        /// </summary>
        internal static string GiveawayJoined_ConfirmedFor {
            get {
                return ResourceManager.GetString("GiveawayJoined_ConfirmedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участие в.
        /// </summary>
        internal static string GiveawayJoined_Join {
            get {
                return ResourceManager.GetString("GiveawayJoined_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на points.
        /// </summary>
        internal static string GiveawayJoined_Points {
            get {
                return ResourceManager.GetString("GiveawayJoined_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не подтверждено.
        /// </summary>
        internal static string GiveawayNotJoined_NotConfirmed {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы должны состоять в группе.
        /// </summary>
        internal static string GiveawayNotJoined_YouMustEnteredToGroup {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_YouMustEnteredToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть выигрыш.
        /// </summary>
        internal static string GiveawaysHaveWon {
            get {
                return ResourceManager.GetString("GiveawaysHaveWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используя программу, вы соглашаетесь с тем, что разработчик не несет ответственности за ваши аккаунты. Все действия инициируются пользователем и только пользователь ответственен за них..
        /// </summary>
        internal static string Licens {
            get {
                return ResourceManager.GetString("Licens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль загружен.
        /// </summary>
        internal static string LoadProfile_Load {
            get {
                return ResourceManager.GetString("LoadProfile_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации.
        /// </summary>
        internal static string LoginFaild {
            get {
                return ResourceManager.GetString("LoginFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизован.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено.
        /// </summary>
        internal static string ParseLoadGiveaways_Found {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено груповых раздач.
        /// </summary>
        internal static string ParseLoadGiveaways_FoundGiveAwaysInGroup {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено раздач в вишлисте.
        /// </summary>
        internal static string ParseLoadGiveaways_FoundGiveAwaysInWishList {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено подходящих раздач.
        /// </summary>
        internal static string ParseLoadGiveaways_FoundMatchGiveaways {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundMatchGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бесплатных золотых раздач на.
        /// </summary>
        internal static string ParseLoadGiveaways_FreeGoldenGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FreeGoldenGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на групповых раздач на.
        /// </summary>
        internal static string ParseLoadGiveaways_GroupGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_GroupGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на страницах.
        /// </summary>
        internal static string ParseLoadGiveaways_Pages {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на обычных раздач на.
        /// </summary>
        internal static string ParseLoadGiveaways_RegularGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_RegularGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на раздач из пеcочницы на.
        /// </summary>
        internal static string ParseLoadGiveaways_SandboxGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SandboxGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на раздач из вишлиста на.
        /// </summary>
        internal static string ParseLoadGiveaways_WishListGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_WishListGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угля.
        /// </summary>
        internal static string ParseProfile_Coal {
            get {
                return ResourceManager.GetString("ParseProfile_Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень.
        /// </summary>
        internal static string ParseProfile_Level {
            get {
                return ResourceManager.GetString("ParseProfile_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка логина/сервера.
        /// </summary>
        internal static string ParseProfile_LoginOrServerError {
            get {
                return ResourceManager.GetString("ParseProfile_LoginOrServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Points.
        /// </summary>
        internal static string ParseProfile_Points {
            get {
                return ResourceManager.GetString("ParseProfile_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже состоите в этой группе.
        /// </summary>
        internal static string SteamGroupAlreadyMember {
            get {
                return ResourceManager.GetString("SteamGroupAlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участие в группе подтверждено.
        /// </summary>
        internal static string SteamGroupJoined {
            get {
                return ResourceManager.GetString("SteamGroupJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участие в группе НЕ подтверждено.
        /// </summary>
        internal static string SteamGroupNotJoined {
            get {
                return ResourceManager.GetString("SteamGroupNotJoined", resourceCulture);
            }
        }
    }
}
