/*
* This is a personal academic project. Dear PVS-Studio, please check it.
* PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryBot.CommonResources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KryBot.CommonResources.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Social links.
        /// </summary>
        public static string AboutForm_groupBox1 {
            get {
                return ResourceManager.GetString("AboutForm_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About program.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account is not activated.
        /// </summary>
        public static string AccountNotActive {
            get {
                return ResourceManager.GetString("AccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KryBot - Agreement.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To perform this task, the application must be run with administrator privileges.
        /// </summary>
        public static string Autorun_MustHaveAdminPerm {
            get {
                return ResourceManager.GetString("Autorun_MustHaveAdminPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When writing to the registry error occurred. Writing to the registry is prohibited by the administrator?.
        /// </summary>
        public static string Autorun_RegisterEditError {
            get {
                return ResourceManager.GetString("Autorun_RegisterEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blacklist.
        /// </summary>
        public static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Need authorization on Steam.
        /// </summary>
        public static string Blacklist_NeedAuth {
            get {
                return ResourceManager.GetString("Blacklist_NeedAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string BlacklistForm_Add {
            get {
                return ResourceManager.GetString("BlacklistForm_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string BlacklistForm_Del {
            get {
                return ResourceManager.GetString("BlacklistForm_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter game ID.
        /// </summary>
        public static string BlacklistForm_EnterId {
            get {
                return ResourceManager.GetString("BlacklistForm_EnterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load from....
        /// </summary>
        public static string BlacklistForm_LoadFrom {
            get {
                return ResourceManager.GetString("BlacklistForm_LoadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam Profile.
        /// </summary>
        public static string BlacklistForm_SteamAccount {
            get {
                return ResourceManager.GetString("BlacklistForm_SteamAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To apply the changes need to restart the application.
        /// </summary>
        public static string CookieForm_MustRestart {
            get {
                return ResourceManager.GetString("CookieForm_MustRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string CookieForm_Save {
            get {
                return ResourceManager.GetString("CookieForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developer Support.
        /// </summary>
        public static string DonateForm_Donate {
            get {
                return ResourceManager.GetString("DonateForm_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can help the developer material transfer any amount to one of the accounts, iven below:.
        /// </summary>
        public static string DonateForm_Text {
            get {
                return ResourceManager.GetString("DonateForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farm.
        /// </summary>
        public static string Farm {
            get {
                return ResourceManager.GetString("Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save profile.
        /// </summary>
        public static string FileDialog_SaveProfile {
            get {
                return ResourceManager.GetString("FileDialog_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farm started ....
        /// </summary>
        public static string FormMain_btnStart_Click_FarmBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farm started at intervals.
        /// </summary>
        public static string FormMain_btnStart_Click_FarmBeginWithInterval {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBeginWithInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farm completed.
        /// </summary>
        public static string FormMain_btnStart_Click_FarmFinish {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skip attempts farm. Previous farming cycle is not yet over..
        /// </summary>
        public static string FormMain_btnStart_Click_FarmSkip {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cycles left).
        /// </summary>
        public static string FormMain_btnStart_Click_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m (.
        /// </summary>
        public static string FormMain_btnStart_Click_M {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string FormMain_btnStart_Click_Stop {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing....
        /// </summary>
        public static string FormMain_btnStart_Click_TaskBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_TaskBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string FormMain_btnStart_Click_Старт {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Старт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farm.
        /// </summary>
        public static string FormMain_DoFarm_Farn {
            get {
                return ResourceManager.GetString("FormMain_DoFarm_Farn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string FormMain_Label_Status {
            get {
                return ResourceManager.GetString("FormMain_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left cycles.
        /// </summary>
        public static string FormMain_timer_Tick_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_timer_Tick_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Games on the blacklist.
        /// </summary>
        public static string GamesInBlacklist {
            get {
                return ResourceManager.GetString("GamesInBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration.
        /// </summary>
        public static string GetBotInConfig_Config {
            get {
                return ResourceManager.GetString("GetBotInConfig_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not loaded. File does not exist or is broken..
        /// </summary>
        public static string GetBotInConfig_NotLoaded {
            get {
                return ResourceManager.GetString("GetBotInConfig_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на confirmed for.
        /// </summary>
        public static string GiveawayJoined_ConfirmedFor {
            get {
                return ResourceManager.GetString("GiveawayJoined_ConfirmedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entry into.
        /// </summary>
        public static string GiveawayJoined_Join {
            get {
                return ResourceManager.GetString("GiveawayJoined_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на points.
        /// </summary>
        public static string GiveawayJoined_Points {
            get {
                return ResourceManager.GetString("GiveawayJoined_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not confirmed.
        /// </summary>
        public static string GiveawayNotJoined_NotConfirmed {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter the group.
        /// </summary>
        public static string GiveawayNotJoined_YouMustEnteredToGroup {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_YouMustEnteredToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you have a win.
        /// </summary>
        public static string GiveawaysHaveWon {
            get {
                return ResourceManager.GetString("GiveawaysHaveWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Using the program, you agree that the developer is not responsible for your accounts. All actions are initiated by the user and the user is responsible for them..
        /// </summary>
        public static string Licens {
            get {
                return ResourceManager.GetString("Licens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To website.
        /// </summary>
        public static string LinkLabel_OnSite {
            get {
                return ResourceManager.GetString("LinkLabel_OnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile loaded.
        /// </summary>
        public static string LoadProfile_Load {
            get {
                return ResourceManager.GetString("LoadProfile_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorisation Error.
        /// </summary>
        public static string LoginFaild {
            get {
                return ResourceManager.GetString("LoginFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorized.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Donate.
        /// </summary>
        public static string MainForm_Donate {
            get {
                return ResourceManager.GetString("MainForm_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update on.
        /// </summary>
        public static string MainForm_UpdateInfoAbout {
            get {
                return ResourceManager.GetString("MainForm_UpdateInfoAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open folder with bot.
        /// </summary>
        public static string OpenBotFolder {
            get {
                return ResourceManager.GetString("OpenBotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contributors giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways__ContributorsIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways__ContributorsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CS:GO items on.
        /// </summary>
        public static string ParseLoadGiveaways_CSGOGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_CSGOGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dota 2 items on.
        /// </summary>
        public static string ParseLoadGiveaways_DotaGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_DotaGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found.
        /// </summary>
        public static string ParseLoadGiveaways_Found {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found group giveaways.
        /// </summary>
        public static string ParseLoadGiveaways_FoundGiveAwaysInGroup {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found wishlist giveaways.
        /// </summary>
        public static string ParseLoadGiveaways_FoundGiveAwaysInWishList {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found matching giveaways.
        /// </summary>
        public static string ParseLoadGiveaways_FoundMatchGiveaways {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundMatchGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на free gold giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_FreeGoldenGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FreeGoldenGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на group giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_GroupGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_GroupGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pages.
        /// </summary>
        public static string ParseLoadGiveaways_Pages {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на regular giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_RegularGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_RegularGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sandbox giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_SandboxGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SandboxGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_SteamGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SteamGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam items on.
        /// </summary>
        public static string ParseLoadGiveaways_SteamItemsIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SteamItemsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TF2 items on.
        /// </summary>
        public static string ParseLoadGiveaways_TF2GiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_TF2GiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на wishlist giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_WishListGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_WishListGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error login/server.
        /// </summary>
        public static string ParseProfile_LoginOrServerError {
            get {
                return ResourceManager.GetString("ParseProfile_LoginOrServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading profile.
        /// </summary>
        public static string ProfileLoading {
            get {
                return ResourceManager.GetString("ProfileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum bet:.
        /// </summary>
        public static string SettingsFform_MaxValue {
            get {
                return ResourceManager.GetString("SettingsFform_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autorun.
        /// </summary>
        public static string SettingsForm_cbAutorun {
            get {
                return ResourceManager.GetString("SettingsForm_cbAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notification about farm.
        /// </summary>
        public static string SettingsForm_cbFarmTip {
            get {
                return ResourceManager.GetString("SettingsForm_cbFarmTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Free golden giveaways.
        /// </summary>
        public static string SettingsForm_cbGMGolden {
            get {
                return ResourceManager.GetString("SettingsForm_cbGMGolden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No regional restrictions.
        /// </summary>
        public static string SettingsForm_cbGMRegional {
            get {
                return ResourceManager.GetString("SettingsForm_cbGMRegional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CS:GO items.
        /// </summary>
        public static string SettingsForm_cbIGCSGO {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGCSGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dota 2 items.
        /// </summary>
        public static string SettingsForm_cbIGDota {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGDota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam giveaways.
        /// </summary>
        public static string SettingsForm_cbIGSteamGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGSteamGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam items.
        /// </summary>
        public static string SettingsForm_cbIGSteamItems {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGSteamItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TF2 items.
        /// </summary>
        public static string SettingsForm_cbIGTF2 {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGTF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto entry into the group (required authorization in Steam).
        /// </summary>
        public static string SettingsForm_cbSCAutojoin {
            get {
                return ResourceManager.GetString("SettingsForm_cbSCAutojoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contributors giveaways.
        /// </summary>
        public static string SettingsForm_cbSCContributors {
            get {
                return ResourceManager.GetString("SettingsForm_cbSCContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The minimum level of giveaways.
        /// </summary>
        public static string SettingsForm_cbSGMinLevel {
            get {
                return ResourceManager.GetString("SettingsForm_cbSGMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First giveaways of the highest level.
        /// </summary>
        public static string SettingsForm_cbSGSortTeLessLevel {
            get {
                return ResourceManager.GetString("SettingsForm_cbSGSortTeLessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First giveaways of the more copies.
        /// </summary>
        public static string SettingsForm_cbSGSortToMoreCopies {
            get {
                return ResourceManager.GetString("SettingsForm_cbSGSortToMoreCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First.
        /// </summary>
        public static string SettingsForm_cbSort {
            get {
                return ResourceManager.GetString("SettingsForm_cbSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        public static string SettingsForm_cbTimerEnable {
            get {
                return ResourceManager.GetString("SettingsForm_cbTimerEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do not use sorting to wishlist.
        /// </summary>
        public static string SettingsForm_cbWishlistSort {
            get {
                return ResourceManager.GetString("SettingsForm_cbWishlistSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notificaions about win.
        /// </summary>
        public static string SettingsForm_cbWonTip {
            get {
                return ResourceManager.GetString("SettingsForm_cbWonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sandbox giveaways.
        /// </summary>
        public static string SettingsForm_chGMSandbox {
            get {
                return ResourceManager.GetString("SettingsForm_chGMSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Common.
        /// </summary>
        public static string SettingsForm_Commun {
            get {
                return ResourceManager.GetString("SettingsForm_Commun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cheap.
        /// </summary>
        public static string SettingsForm_FirstCheap {
            get {
                return ResourceManager.GetString("SettingsForm_FirstCheap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на expensive.
        /// </summary>
        public static string SettingsForm_FirstExpensive {
            get {
                return ResourceManager.GetString("SettingsForm_FirstExpensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsForm_gbTimerSettings {
            get {
                return ResourceManager.GetString("SettingsForm_gbTimerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timer.
        /// </summary>
        public static string SettingsForm_groupBox1 {
            get {
                return ResourceManager.GetString("SettingsForm_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group giveaways.
        /// </summary>
        public static string SettingsForm_GroupGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_GroupGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The interval timer can not be 0.
        /// </summary>
        public static string SettingsForm_IntervalNotZero {
            get {
                return ResourceManager.GetString("SettingsForm_IntervalNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interval:.
        /// </summary>
        public static string SettingsForm_label5 {
            get {
                return ResourceManager.GetString("SettingsForm_label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m.
        /// </summary>
        public static string SettingsForm_label6 {
            get {
                return ResourceManager.GetString("SettingsForm_label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsForm_label7 {
            get {
                return ResourceManager.GetString("SettingsForm_label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cycles:.
        /// </summary>
        public static string SettingsForm_label8 {
            get {
                return ResourceManager.GetString("SettingsForm_label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reserve points:.
        /// </summary>
        public static string SettingsForm_PointsReserv {
            get {
                return ResourceManager.GetString("SettingsForm_PointsReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regular giveaways.
        /// </summary>
        public static string SettingsForm_RegularGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_RegularGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wishlist.
        /// </summary>
        public static string SettingsForm_WishlistGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_WishlistGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create shortcut.
        /// </summary>
        public static string Settngs_CreateShortcut {
            get {
                return ResourceManager.GetString("Settngs_CreateShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not authorized.
        /// </summary>
        public static string Status_NotLogined {
            get {
                return ResourceManager.GetString("Status_NotLogined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed.
        /// </summary>
        public static string StatusBar_End {
            get {
                return ResourceManager.GetString("StatusBar_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string StatusBar_Login {
            get {
                return ResourceManager.GetString("StatusBar_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You already are a member of this group.
        /// </summary>
        public static string SteamGroupAlreadyMember {
            get {
                return ResourceManager.GetString("SteamGroupAlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Joining the group confirmed.
        /// </summary>
        public static string SteamGroupJoined {
            get {
                return ResourceManager.GetString("SteamGroupJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Joining the group is not confirmed.
        /// </summary>
        public static string SteamGroupNotJoined {
            get {
                return ResourceManager.GetString("SteamGroupNotJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization....
        /// </summary>
        public static string TryLogin {
            get {
                return ResourceManager.GetString("TryLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current version.
        /// </summary>
        public static string Updater_CurrentVersion {
            get {
                return ResourceManager.GetString("Updater_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update available.
        /// </summary>
        public static string Updater_HaveUpdate {
            get {
                return ResourceManager.GetString("Updater_HaveUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The update is complete. Restarting....
        /// </summary>
        public static string Updater_Update_UpdateDone {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When updating the error occurred. Download the manual: https://github.com/KriBetko/KryBot/releases.
        /// </summary>
        public static string Updater_Update_UpdateFailed {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
