//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryBot.CommonResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KryBot.CommonResources.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social links.
        /// </summary>
        public static string AboutForm_groupBox1 {
            get {
                return ResourceManager.GetString("AboutForm_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not activated.
        /// </summary>
        public static string AccountNotActive {
            get {
                return ResourceManager.GetString("AccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KryBot - Agreement.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To perform this task, the application must be run with administrator privileges.
        /// </summary>
        public static string Autorun_MustHaveAdminPerm {
            get {
                return ResourceManager.GetString("Autorun_MustHaveAdminPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When writing to the registry error occurred. Writing to the registry is prohibited by the administrator?.
        /// </summary>
        public static string Autorun_RegisterEditError {
            get {
                return ResourceManager.GetString("Autorun_RegisterEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need authorization on Steam.
        /// </summary>
        public static string Blacklist_NeedAuth {
            get {
                return ResourceManager.GetString("Blacklist_NeedAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BlacklistForm_Add {
            get {
                return ResourceManager.GetString("BlacklistForm_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BlacklistForm_Del {
            get {
                return ResourceManager.GetString("BlacklistForm_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from....
        /// </summary>
        public static string BlacklistForm_LoadFrom {
            get {
                return ResourceManager.GetString("BlacklistForm_LoadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Profile.
        /// </summary>
        public static string BlacklistForm_SteamAccount {
            get {
                return ResourceManager.GetString("BlacklistForm_SteamAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the changes need to restart the application.
        /// </summary>
        public static string CookieForm_MustRestart {
            get {
                return ResourceManager.GetString("CookieForm_MustRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CookieForm_Save {
            get {
                return ResourceManager.GetString("CookieForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Support.
        /// </summary>
        public static string DonateForm_Donate {
            get {
                return ResourceManager.GetString("DonateForm_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can help the developer material transfer any amount to one of the accounts, iven below:.
        /// </summary>
        public static string DonateForm_Text {
            get {
                return ResourceManager.GetString("DonateForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        public static string Farm {
            get {
                return ResourceManager.GetString("Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile.
        /// </summary>
        public static string FileDialog_SaveProfile {
            get {
                return ResourceManager.GetString("FileDialog_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm started ....
        /// </summary>
        public static string FormMain_btnStart_Click_FarmBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm started at intervals.
        /// </summary>
        public static string FormMain_btnStart_Click_FarmBeginWithInterval {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBeginWithInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm completed.
        /// </summary>
        public static string FormMain_btnStart_Click_FarmFinish {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip attempts farm. Previous farming cycle is not yet over..
        /// </summary>
        public static string FormMain_btnStart_Click_FarmSkip {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cycles left).
        /// </summary>
        public static string FormMain_btnStart_Click_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m (.
        /// </summary>
        public static string FormMain_btnStart_Click_M {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string FormMain_btnStart_Click_Stop {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string FormMain_btnStart_Click_TaskBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_TaskBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string FormMain_btnStart_Click_Старт {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Старт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        public static string FormMain_DoFarm_Farn {
            get {
                return ResourceManager.GetString("FormMain_DoFarm_Farn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FormMain_Label_Status {
            get {
                return ResourceManager.GetString("FormMain_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left cycles.
        /// </summary>
        public static string FormMain_timer_Tick_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_timer_Tick_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games on the blacklist.
        /// </summary>
        public static string GamesInBlacklist {
            get {
                return ResourceManager.GetString("GamesInBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string GetBotInConfig_Config {
            get {
                return ResourceManager.GetString("GetBotInConfig_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not loaded. File does not exist or is broken..
        /// </summary>
        public static string GetBotInConfig_NotLoaded {
            get {
                return ResourceManager.GetString("GetBotInConfig_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmed for.
        /// </summary>
        public static string GiveawayJoined_ConfirmedFor {
            get {
                return ResourceManager.GetString("GiveawayJoined_ConfirmedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry into.
        /// </summary>
        public static string GiveawayJoined_Join {
            get {
                return ResourceManager.GetString("GiveawayJoined_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string GiveawayJoined_Points {
            get {
                return ResourceManager.GetString("GiveawayJoined_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not confirmed.
        /// </summary>
        public static string GiveawayNotJoined_NotConfirmed {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the group.
        /// </summary>
        public static string GiveawayNotJoined_YouMustEnteredToGroup {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_YouMustEnteredToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a win.
        /// </summary>
        public static string GiveawaysHaveWon {
            get {
                return ResourceManager.GetString("GiveawaysHaveWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the program, you agree that the developer is not responsible for your accounts. All actions are initiated by the user and the user is responsible for them..
        /// </summary>
        public static string Licens {
            get {
                return ResourceManager.GetString("Licens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To website.
        /// </summary>
        public static string LinkLabel_OnSite {
            get {
                return ResourceManager.GetString("LinkLabel_OnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile loaded.
        /// </summary>
        public static string LoadProfile_Load {
            get {
                return ResourceManager.GetString("LoadProfile_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorisation Error.
        /// </summary>
        public static string LoginFaild {
            get {
                return ResourceManager.GetString("LoginFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string MainForm_Donate {
            get {
                return ResourceManager.GetString("MainForm_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update on.
        /// </summary>
        public static string MainForm_UpdateInfoAbout {
            get {
                return ResourceManager.GetString("MainForm_UpdateInfoAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder with bot.
        /// </summary>
        public static string OpenBotFolder {
            get {
                return ResourceManager.GetString("OpenBotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contributors giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways__ContributorsIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways__ContributorsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS:GO items on.
        /// </summary>
        public static string ParseLoadGiveaways_CSGOGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_CSGOGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dota 2 items on.
        /// </summary>
        public static string ParseLoadGiveaways_DotaGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_DotaGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string ParseLoadGiveaways_Found {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found group giveaways.
        /// </summary>
        public static string ParseLoadGiveaways_FoundGiveAwaysInGroup {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found wishlist giveaways.
        /// </summary>
        public static string ParseLoadGiveaways_FoundGiveAwaysInWishList {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found matching giveaways.
        /// </summary>
        public static string ParseLoadGiveaways_FoundMatchGiveaways {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundMatchGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free gold giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_FreeGoldenGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FreeGoldenGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_GroupGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_GroupGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        public static string ParseLoadGiveaways_Pages {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regular giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_RegularGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_RegularGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sandbox giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_SandboxGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SandboxGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_SteamGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SteamGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam items on.
        /// </summary>
        public static string ParseLoadGiveaways_SteamItemsIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SteamItemsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF2 items on.
        /// </summary>
        public static string ParseLoadGiveaways_TF2GiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_TF2GiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wishlist giveaways on.
        /// </summary>
        public static string ParseLoadGiveaways_WishListGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_WishListGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error login/server.
        /// </summary>
        public static string ParseProfile_LoginOrServerError {
            get {
                return ResourceManager.GetString("ParseProfile_LoginOrServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading profile.
        /// </summary>
        public static string ProfileLoading {
            get {
                return ResourceManager.GetString("ProfileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum bet:.
        /// </summary>
        public static string SettingsFform_MaxValue {
            get {
                return ResourceManager.GetString("SettingsFform_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorun.
        /// </summary>
        public static string SettingsForm_cbAutorun {
            get {
                return ResourceManager.GetString("SettingsForm_cbAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification about farm.
        /// </summary>
        public static string SettingsForm_cbFarmTip {
            get {
                return ResourceManager.GetString("SettingsForm_cbFarmTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free golden giveaways.
        /// </summary>
        public static string SettingsForm_cbGMGolden {
            get {
                return ResourceManager.GetString("SettingsForm_cbGMGolden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No regional restrictions.
        /// </summary>
        public static string SettingsForm_cbGMRegional {
            get {
                return ResourceManager.GetString("SettingsForm_cbGMRegional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS:GO items.
        /// </summary>
        public static string SettingsForm_cbIGCSGO {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGCSGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dota 2 items.
        /// </summary>
        public static string SettingsForm_cbIGDota {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGDota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam giveaways.
        /// </summary>
        public static string SettingsForm_cbIGSteamGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGSteamGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam items.
        /// </summary>
        public static string SettingsForm_cbIGSteamItems {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGSteamItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF2 items.
        /// </summary>
        public static string SettingsForm_cbIGTF2 {
            get {
                return ResourceManager.GetString("SettingsForm_cbIGTF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic entry into the group (required authorization in Steam).
        /// </summary>
        public static string SettingsForm_cbSCAutojoin {
            get {
                return ResourceManager.GetString("SettingsForm_cbSCAutojoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors giveaways.
        /// </summary>
        public static string SettingsForm_cbSCContributors {
            get {
                return ResourceManager.GetString("SettingsForm_cbSCContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum level of giveaways.
        /// </summary>
        public static string SettingsForm_cbSGMinLevel {
            get {
                return ResourceManager.GetString("SettingsForm_cbSGMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First giveaways of the highest level.
        /// </summary>
        public static string SettingsForm_cbSGSortTeLessLevel {
            get {
                return ResourceManager.GetString("SettingsForm_cbSGSortTeLessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string SettingsForm_cbSort {
            get {
                return ResourceManager.GetString("SettingsForm_cbSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string SettingsForm_cbTimerEnable {
            get {
                return ResourceManager.GetString("SettingsForm_cbTimerEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use sorting to wishlist.
        /// </summary>
        public static string SettingsForm_cbWishlistSort {
            get {
                return ResourceManager.GetString("SettingsForm_cbWishlistSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaions about win.
        /// </summary>
        public static string SettingsForm_cbWonTip {
            get {
                return ResourceManager.GetString("SettingsForm_cbWonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox giveaways.
        /// </summary>
        public static string SettingsForm_chGMSandbox {
            get {
                return ResourceManager.GetString("SettingsForm_chGMSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string SettingsForm_Commun {
            get {
                return ResourceManager.GetString("SettingsForm_Commun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsForm_gbTimerSettings {
            get {
                return ResourceManager.GetString("SettingsForm_gbTimerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string SettingsForm_groupBox1 {
            get {
                return ResourceManager.GetString("SettingsForm_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group giveaways.
        /// </summary>
        public static string SettingsForm_GroupGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_GroupGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval timer can not be 0.
        /// </summary>
        public static string SettingsForm_IntervalNotZero {
            get {
                return ResourceManager.GetString("SettingsForm_IntervalNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval:.
        /// </summary>
        public static string SettingsForm_label5 {
            get {
                return ResourceManager.GetString("SettingsForm_label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string SettingsForm_label6 {
            get {
                return ResourceManager.GetString("SettingsForm_label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsForm_label7 {
            get {
                return ResourceManager.GetString("SettingsForm_label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles:.
        /// </summary>
        public static string SettingsForm_label8 {
            get {
                return ResourceManager.GetString("SettingsForm_label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve points:.
        /// </summary>
        public static string SettingsForm_PointsReserv {
            get {
                return ResourceManager.GetString("SettingsForm_PointsReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular giveaways.
        /// </summary>
        public static string SettingsForm_RegularGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_RegularGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string SettingsForm_WishlistGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_WishlistGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        public static string Status_NotLogined {
            get {
                return ResourceManager.GetString("Status_NotLogined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string StatusBar_End {
            get {
                return ResourceManager.GetString("StatusBar_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string StatusBar_Login {
            get {
                return ResourceManager.GetString("StatusBar_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already are a member of this group.
        /// </summary>
        public static string SteamGroupAlreadyMember {
            get {
                return ResourceManager.GetString("SteamGroupAlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining the group confirmed.
        /// </summary>
        public static string SteamGroupJoined {
            get {
                return ResourceManager.GetString("SteamGroupJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining the group is not confirmed.
        /// </summary>
        public static string SteamGroupNotJoined {
            get {
                return ResourceManager.GetString("SteamGroupNotJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization....
        /// </summary>
        public static string TryLogin {
            get {
                return ResourceManager.GetString("TryLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        public static string Updater_CurrentVersion {
            get {
                return ResourceManager.GetString("Updater_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string Updater_HaveUpdate {
            get {
                return ResourceManager.GetString("Updater_HaveUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update is complete. Restarting....
        /// </summary>
        public static string Updater_Update_UpdateDone {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When updating the error occurred.
        /// </summary>
        public static string Updater_Update_UpdateFailed {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
