//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryBot.CommonResources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KryBot.CommonResources.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ссылки на сообщества.
        /// </summary>
        public static string AboutForm_groupBox1 {
            get {
                return ResourceManager.GetString("AboutForm_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт не активирован.
        /// </summary>
        public static string AccountNotActive {
            get {
                return ResourceManager.GetString("AccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KryBot - Соглашение.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выполнения этого действия приложение должно быть запущен с правами администратора.
        /// </summary>
        public static string Autorun_MustHaveAdminPerm {
            get {
                return ResourceManager.GetString("Autorun_MustHaveAdminPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При записи в реестр произошла ошибка. Запись в реестр запрещена администратором?.
        /// </summary>
        public static string Autorun_RegisterEditError {
            get {
                return ResourceManager.GetString("Autorun_RegisterEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Черный список.
        /// </summary>
        public static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужна авторизация в Steam.
        /// </summary>
        public static string Blacklist_NeedAuth {
            get {
                return ResourceManager.GetString("Blacklist_NeedAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string BlacklistForm_Add {
            get {
                return ResourceManager.GetString("BlacklistForm_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string BlacklistForm_Del {
            get {
                return ResourceManager.GetString("BlacklistForm_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить из....
        /// </summary>
        public static string BlacklistForm_LoadFrom {
            get {
                return ResourceManager.GetString("BlacklistForm_LoadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль Steam.
        /// </summary>
        public static string BlacklistForm_SteamAccount {
            get {
                return ResourceManager.GetString("BlacklistForm_SteamAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для применения измененией нужен перезапуск приложения..
        /// </summary>
        public static string CookieForm_MustRestart {
            get {
                return ResourceManager.GetString("CookieForm_MustRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string CookieForm_Save {
            get {
                return ResourceManager.GetString("CookieForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поддержать разработчика.
        /// </summary>
        public static string DonateForm_Donate {
            get {
                return ResourceManager.GetString("DonateForm_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете помочь разработчику материально
        ///перевести любую сумму на один из счетов,
        ///предоставленных ниже:.
        /// </summary>
        public static string DonateForm_Text {
            get {
                return ResourceManager.GetString("DonateForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фарм.
        /// </summary>
        public static string Farm {
            get {
                return ResourceManager.GetString("Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить профиль.
        /// </summary>
        public static string FileDialog_SaveProfile {
            get {
                return ResourceManager.GetString("FileDialog_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершено.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фарм запущен....
        /// </summary>
        public static string FormMain_btnStart_Click_FarmBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фарм запущен с интервалом .
        /// </summary>
        public static string FormMain_btnStart_Click_FarmBeginWithInterval {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBeginWithInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фарм завершен.
        /// </summary>
        public static string FormMain_btnStart_Click_FarmFinish {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропуск попытки фарма. Предыдущий цикл фарма еще не окончен..
        /// </summary>
        public static string FormMain_btnStart_Click_FarmSkip {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  циклов осталось).
        /// </summary>
        public static string FormMain_btnStart_Click_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м (.
        /// </summary>
        public static string FormMain_btnStart_Click_M {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоп.
        /// </summary>
        public static string FormMain_btnStart_Click_Stop {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполняется....
        /// </summary>
        public static string FormMain_btnStart_Click_TaskBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_TaskBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт.
        /// </summary>
        public static string FormMain_btnStart_Click_Старт {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Старт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фарм.
        /// </summary>
        public static string FormMain_DoFarm_Farn {
            get {
                return ResourceManager.GetString("FormMain_DoFarm_Farn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string FormMain_Label_Status {
            get {
                return ResourceManager.GetString("FormMain_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осталось циклов.
        /// </summary>
        public static string FormMain_timer_Tick_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_timer_Tick_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игр в Blacklist&apos;e.
        /// </summary>
        public static string GamesInBlacklist {
            get {
                return ResourceManager.GetString("GamesInBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация.
        /// </summary>
        public static string GetBotInConfig_Config {
            get {
                return ResourceManager.GetString("GetBotInConfig_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не загружена. Файл не существует или сломан..
        /// </summary>
        public static string GetBotInConfig_NotLoaded {
            get {
                return ResourceManager.GetString("GetBotInConfig_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на подтверждено за.
        /// </summary>
        public static string GiveawayJoined_ConfirmedFor {
            get {
                return ResourceManager.GetString("GiveawayJoined_ConfirmedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участие в.
        /// </summary>
        public static string GiveawayJoined_Join {
            get {
                return ResourceManager.GetString("GiveawayJoined_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на points.
        /// </summary>
        public static string GiveawayJoined_Points {
            get {
                return ResourceManager.GetString("GiveawayJoined_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не подтверждено.
        /// </summary>
        public static string GiveawayNotJoined_NotConfirmed {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы должны состоять в группе.
        /// </summary>
        public static string GiveawayNotJoined_YouMustEnteredToGroup {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_YouMustEnteredToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть выигрыш.
        /// </summary>
        public static string GiveawaysHaveWon {
            get {
                return ResourceManager.GetString("GiveawaysHaveWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используя программу, вы соглашаетесь с тем, что разработчик не несет ответственности за ваши аккаунты. Все действия инициируются пользователем и только пользователь ответственен за них..
        /// </summary>
        public static string Licens {
            get {
                return ResourceManager.GetString("Licens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На сайт.
        /// </summary>
        public static string LinkLabel_OnSite {
            get {
                return ResourceManager.GetString("LinkLabel_OnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль загружен.
        /// </summary>
        public static string LoadProfile_Load {
            get {
                return ResourceManager.GetString("LoadProfile_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лог.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации.
        /// </summary>
        public static string LoginFaild {
            get {
                return ResourceManager.GetString("LoginFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизован.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поддержать.
        /// </summary>
        public static string MainForm_Donate {
            get {
                return ResourceManager.GetString("MainForm_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление информации о.
        /// </summary>
        public static string MainForm_UpdateInfoAbout {
            get {
                return ResourceManager.GetString("MainForm_UpdateInfoAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть папку с ботом.
        /// </summary>
        public static string OpenBotFolder {
            get {
                return ResourceManager.GetString("OpenBotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contributors раздач на.
        /// </summary>
        public static string ParseLoadGiveaways__ContributorsIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways__ContributorsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено.
        /// </summary>
        public static string ParseLoadGiveaways_Found {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено груповых раздач.
        /// </summary>
        public static string ParseLoadGiveaways_FoundGiveAwaysInGroup {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено раздач в вишлисте.
        /// </summary>
        public static string ParseLoadGiveaways_FoundGiveAwaysInWishList {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено подходящих раздач.
        /// </summary>
        public static string ParseLoadGiveaways_FoundMatchGiveaways {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundMatchGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бесплатных золотых раздач на.
        /// </summary>
        public static string ParseLoadGiveaways_FreeGoldenGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FreeGoldenGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на групповых раздач на.
        /// </summary>
        public static string ParseLoadGiveaways_GroupGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_GroupGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на страницах.
        /// </summary>
        public static string ParseLoadGiveaways_Pages {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на обычных раздач на.
        /// </summary>
        public static string ParseLoadGiveaways_RegularGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_RegularGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на раздач из пеcочницы на.
        /// </summary>
        public static string ParseLoadGiveaways_SandboxGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SandboxGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на раздач из вишлиста на.
        /// </summary>
        public static string ParseLoadGiveaways_WishListGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_WishListGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка логина/сервера.
        /// </summary>
        public static string ParseProfile_LoginOrServerError {
            get {
                return ResourceManager.GetString("ParseProfile_LoginOrServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка профиля.
        /// </summary>
        public static string ProfileLoading {
            get {
                return ResourceManager.GetString("ProfileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить как....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная ставка:.
        /// </summary>
        public static string SettingsFform_MaxValue {
            get {
                return ResourceManager.GetString("SettingsFform_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автозагрузка.
        /// </summary>
        public static string SettingsForm_cbAutorun {
            get {
                return ResourceManager.GetString("SettingsForm_cbAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оповещение о фарме.
        /// </summary>
        public static string SettingsForm_cbFarmTip {
            get {
                return ResourceManager.GetString("SettingsForm_cbFarmTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бесплатные золотые раздачи.
        /// </summary>
        public static string SettingsForm_cbGMGolden {
            get {
                return ResourceManager.GetString("SettingsForm_cbGMGolden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без региональных ограничений.
        /// </summary>
        public static string SettingsForm_cbGMRegional {
            get {
                return ResourceManager.GetString("SettingsForm_cbGMRegional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автовступление в группы (нужна авторизация в Steam).
        /// </summary>
        public static string SettingsForm_cbSCAutojoin {
            get {
                return ResourceManager.GetString("SettingsForm_cbSCAutojoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contributors раздачи.
        /// </summary>
        public static string SettingsForm_cbSCContributors {
            get {
                return ResourceManager.GetString("SettingsForm_cbSCContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальный уровень раздач.
        /// </summary>
        public static string SettingsForm_cbSGMinLevel {
            get {
                return ResourceManager.GetString("SettingsForm_cbSGMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала раздачи наивысшего уровня.
        /// </summary>
        public static string SettingsForm_cbSGSortTeLessLevel {
            get {
                return ResourceManager.GetString("SettingsForm_cbSGSortTeLessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала.
        /// </summary>
        public static string SettingsForm_cbSort {
            get {
                return ResourceManager.GetString("SettingsForm_cbSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включен.
        /// </summary>
        public static string SettingsForm_cbTimerEnable {
            get {
                return ResourceManager.GetString("SettingsForm_cbTimerEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не применять сортировку к вишлисту.
        /// </summary>
        public static string SettingsForm_cbWishlistSort {
            get {
                return ResourceManager.GetString("SettingsForm_cbWishlistSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оповещение о победах.
        /// </summary>
        public static string SettingsForm_cbWonTip {
            get {
                return ResourceManager.GetString("SettingsForm_cbWonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раздачи из песочницы.
        /// </summary>
        public static string SettingsForm_chGMSandbox {
            get {
                return ResourceManager.GetString("SettingsForm_chGMSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие.
        /// </summary>
        public static string SettingsForm_Commun {
            get {
                return ResourceManager.GetString("SettingsForm_Commun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string SettingsForm_gbTimerSettings {
            get {
                return ResourceManager.GetString("SettingsForm_gbTimerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таймер.
        /// </summary>
        public static string SettingsForm_groupBox1 {
            get {
                return ResourceManager.GetString("SettingsForm_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Групповые раздачи.
        /// </summary>
        public static string SettingsForm_GroupGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_GroupGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал таймера не может равняться 0.
        /// </summary>
        public static string SettingsForm_IntervalNotZero {
            get {
                return ResourceManager.GetString("SettingsForm_IntervalNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал:.
        /// </summary>
        public static string SettingsForm_label5 {
            get {
                return ResourceManager.GetString("SettingsForm_label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м.
        /// </summary>
        public static string SettingsForm_label6 {
            get {
                return ResourceManager.GetString("SettingsForm_label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на шт.
        /// </summary>
        public static string SettingsForm_label7 {
            get {
                return ResourceManager.GetString("SettingsForm_label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Циклов: .
        /// </summary>
        public static string SettingsForm_label8 {
            get {
                return ResourceManager.GetString("SettingsForm_label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резерв points:.
        /// </summary>
        public static string SettingsForm_PointsReserv {
            get {
                return ResourceManager.GetString("SettingsForm_PointsReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обычные раздачи.
        /// </summary>
        public static string SettingsForm_RegularGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_RegularGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wishlist.
        /// </summary>
        public static string SettingsForm_WishlistGiveaways {
            get {
                return ResourceManager.GetString("SettingsForm_WishlistGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развернуть.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт....
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не авторизован.
        /// </summary>
        public static string Status_NotLogined {
            get {
                return ResourceManager.GetString("Status_NotLogined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершено.
        /// </summary>
        public static string StatusBar_End {
            get {
                return ResourceManager.GetString("StatusBar_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        public static string StatusBar_Login {
            get {
                return ResourceManager.GetString("StatusBar_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже состоите в этой группе.
        /// </summary>
        public static string SteamGroupAlreadyMember {
            get {
                return ResourceManager.GetString("SteamGroupAlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участие в группе подтверждено.
        /// </summary>
        public static string SteamGroupJoined {
            get {
                return ResourceManager.GetString("SteamGroupJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участие в группе НЕ подтверждено.
        /// </summary>
        public static string SteamGroupNotJoined {
            get {
                return ResourceManager.GetString("SteamGroupNotJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервис.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация....
        /// </summary>
        public static string TryLogin {
            get {
                return ResourceManager.GetString("TryLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актуальная версия.
        /// </summary>
        public static string Updater_CurrentVersion {
            get {
                return ResourceManager.GetString("Updater_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно обновление.
        /// </summary>
        public static string Updater_HaveUpdate {
            get {
                return ResourceManager.GetString("Updater_HaveUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление завершено. Перезапуск....
        /// </summary>
        public static string Updater_Update_UpdateDone {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обновлении произошла ошибка.
        /// </summary>
        public static string Updater_Update_UpdateFailed {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
