//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryBot.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KryBot.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт не активирван.
        /// </summary>
        internal static string AccountNotActive {
            get {
                return ResourceManager.GetString("AccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KryBot - Соглашение.
        /// </summary>
        internal static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Угля.
        /// </summary>
        internal static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Библиотека .
        /// </summary>
        internal static string DllNotLoad {
            get {
                return ResourceManager.GetString("DllNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не была загружена. .
        /// </summary>
        internal static string DllNotLoad_1 {
            get {
                return ResourceManager.GetString("DllNotLoad_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершено.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фарм запущен....
        /// </summary>
        internal static string FormMain_btnStart_Click_FarmBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фарм запущен с интервалом .
        /// </summary>
        internal static string FormMain_btnStart_Click_FarmBeginWithInterval {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBeginWithInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фарм завершен.
        /// </summary>
        internal static string FormMain_btnStart_Click_FarmFinish {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропуск попытки фарма. Предыдущий цикл фарма еше не окончен..
        /// </summary>
        internal static string FormMain_btnStart_Click_FarmSkip {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  циклов осталось).
        /// </summary>
        internal static string FormMain_btnStart_Click_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м (.
        /// </summary>
        internal static string FormMain_btnStart_Click_M {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        internal static string FormMain_btnStart_Click_Stop {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется....
        /// </summary>
        internal static string FormMain_btnStart_Click_TaskBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_TaskBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт.
        /// </summary>
        internal static string FormMain_btnStart_Click_Старт {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Старт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фарм.
        /// </summary>
        internal static string FormMain_DoFarm_Farn {
            get {
                return ResourceManager.GetString("FormMain_DoFarm_Farn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string FormMain_Label_Status {
            get {
                return ResourceManager.GetString("FormMain_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осталось циклов.
        /// </summary>
        internal static string FormMain_timer_Tick_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_timer_Tick_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурация.
        /// </summary>
        internal static string GetBotInConfig_Config {
            get {
                return ResourceManager.GetString("GetBotInConfig_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не загружена. Файл не существует или сломан..
        /// </summary>
        internal static string GetBotInConfig_NotLoaded {
            get {
                return ResourceManager.GetString("GetBotInConfig_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to угля.
        /// </summary>
        internal static string GiveawayJoined_Coal {
            get {
                return ResourceManager.GetString("GiveawayJoined_Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подтверждено за.
        /// </summary>
        internal static string GiveawayJoined_ConfirmedFor {
            get {
                return ResourceManager.GetString("GiveawayJoined_ConfirmedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие в.
        /// </summary>
        internal static string GiveawayJoined_Join {
            get {
                return ResourceManager.GetString("GiveawayJoined_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        internal static string GiveawayJoined_Points {
            get {
                return ResourceManager.GetString("GiveawayJoined_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не подтверждено.
        /// </summary>
        internal static string GiveawayNotJoined_NotConfirmed {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны состоять в группе.
        /// </summary>
        internal static string GiveawayNotJoined_YouMustEnteredToGroup {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_YouMustEnteredToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас есть выигрыш.
        /// </summary>
        internal static string GiveawaysHaveWon {
            get {
                return ResourceManager.GetString("GiveawaysHaveWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас устаревшая версия Internet Explorer. Чтобы избежать проблем с работой программы, рекомендуется обновить. Перейти на сайт Microsoft для скачивания обновления?.
        /// </summary>
        internal static string IECheck {
            get {
                return ResourceManager.GetString("IECheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень
        ///.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используя программу, вы соглашаетесь с тем, что разработчик не несет ответственности за ваши аккаунты. Все действия инициируются пользователем и только пользователь ответственен за них..
        /// </summary>
        internal static string Licens {
            get {
                return ResourceManager.GetString("Licens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль загружен.
        /// </summary>
        internal static string LoadProfile_Load {
            get {
                return ResourceManager.GetString("LoadProfile_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка авторизации.
        /// </summary>
        internal static string LoginFaild {
            get {
                return ResourceManager.GetString("LoginFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизован.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contributors раздач на.
        /// </summary>
        internal static string ParseLoadGiveaways__ContributorsIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways__ContributorsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено.
        /// </summary>
        internal static string ParseLoadGiveaways_Found {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено груповых раздач.
        /// </summary>
        internal static string ParseLoadGiveaways_FoundGiveAwaysInGroup {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено раздач с минимальным количеством копий.
        /// </summary>
        internal static string ParseLoadGiveaways_FoundGiveAwaysInMinNumberCopies {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInMinNumberCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено раздач с региональными ограничениями.
        /// </summary>
        internal static string ParseLoadGiveaways_FoundGiveAwaysInRegion {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено раздач в вишлисте.
        /// </summary>
        internal static string ParseLoadGiveaways_FoundGiveAwaysInWishList {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено подходящих раздач.
        /// </summary>
        internal static string ParseLoadGiveaways_FoundMatchGiveaways {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundMatchGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бесплатных золотых раздач на.
        /// </summary>
        internal static string ParseLoadGiveaways_FreeGoldenGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FreeGoldenGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to групповых раздач на.
        /// </summary>
        internal static string ParseLoadGiveaways_GroupGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_GroupGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to страницах.
        /// </summary>
        internal static string ParseLoadGiveaways_Pages {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обычных раздач на.
        /// </summary>
        internal static string ParseLoadGiveaways_RegularGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_RegularGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раздач из пеcочницы на.
        /// </summary>
        internal static string ParseLoadGiveaways_SandboxGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SandboxGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раздач из вишлиста на.
        /// </summary>
        internal static string ParseLoadGiveaways_WishListGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_WishListGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Угля.
        /// </summary>
        internal static string ParseProfile_Coal {
            get {
                return ResourceManager.GetString("ParseProfile_Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень.
        /// </summary>
        internal static string ParseProfile_Level {
            get {
                return ResourceManager.GetString("ParseProfile_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка логина/сервера.
        /// </summary>
        internal static string ParseProfile_LoginOrServerError {
            get {
                return ResourceManager.GetString("ParseProfile_LoginOrServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string ParseProfile_Points {
            get {
                return ResourceManager.GetString("ParseProfile_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт....
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершено.
        /// </summary>
        internal static string StatusBar_End {
            get {
                return ResourceManager.GetString("StatusBar_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        internal static string StatusBar_Login {
            get {
                return ResourceManager.GetString("StatusBar_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже состоите в этой группе.
        /// </summary>
        internal static string SteamGroupAlreadyMember {
            get {
                return ResourceManager.GetString("SteamGroupAlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие в группе подтверждено.
        /// </summary>
        internal static string SteamGroupJoined {
            get {
                return ResourceManager.GetString("SteamGroupJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие в группе НЕ подтверждено.
        /// </summary>
        internal static string SteamGroupNotJoined {
            get {
                return ResourceManager.GetString("SteamGroupNotJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация....
        /// </summary>
        internal static string TryLogin {
            get {
                return ResourceManager.GetString("TryLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление завершено. Перезапуск....
        /// </summary>
        internal static string Updater_Update_UpdateDone {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При обновлении произошла ошибка.
        /// </summary>
        internal static string Updater_Update_UpdateFailed {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
