//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryBot.CommonResources.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KryBot.CommonResources.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылки на сообщества.
        /// </summary>
        public static string AboutForm_groupBox1 {
            get {
                return ResourceManager.GetString("AboutForm_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт не активирван.
        /// </summary>
        public static string AccountNotActive {
            get {
                return ResourceManager.GetString("AccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KryBot - Соглашение.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выполнения этого действия приложение должно быть запущено с правами администратора.
        /// </summary>
        public static string Autorun_MustHaveAdminPerm {
            get {
                return ResourceManager.GetString("Autorun_MustHaveAdminPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При записи в реестр произошла ошибка. Запись в реестр разрешена администратором?.
        /// </summary>
        public static string Autorun_RegisterEditError {
            get {
                return ResourceManager.GetString("Autorun_RegisterEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черный список.
        /// </summary>
        public static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужна авторизация в Steam.
        /// </summary>
        public static string Blacklist_NeedAuth {
            get {
                return ResourceManager.GetString("Blacklist_NeedAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string BlacklistForm_Add {
            get {
                return ResourceManager.GetString("BlacklistForm_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string BlacklistForm_Del {
            get {
                return ResourceManager.GetString("BlacklistForm_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить из....
        /// </summary>
        public static string BlacklistForm_LoadFrom {
            get {
                return ResourceManager.GetString("BlacklistForm_LoadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль Steam.
        /// </summary>
        public static string BlacklistForm_SteamAccount {
            get {
                return ResourceManager.GetString("BlacklistForm_SteamAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Угля.
        /// </summary>
        public static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для применения измененией нужен перезапуск приложения..
        /// </summary>
        public static string CookieForm_MustRestart {
            get {
                return ResourceManager.GetString("CookieForm_MustRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string CookieForm_Save {
            get {
                return ResourceManager.GetString("CookieForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Библиотека .
        /// </summary>
        public static string DllNotLoad {
            get {
                return ResourceManager.GetString("DllNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не была загружена. .
        /// </summary>
        public static string DllNotLoad_1 {
            get {
                return ResourceManager.GetString("DllNotLoad_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержать разработчика.
        /// </summary>
        public static string DonateForm_Donate {
            get {
                return ResourceManager.GetString("DonateForm_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете помочь разработчику материально 
        ///переведя любую сумму на один из счетов, 
        ///предоставленных ниже:.
        /// </summary>
        public static string DonateForm_Text {
            get {
                return ResourceManager.GetString("DonateForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фарм.
        /// </summary>
        public static string Farm {
            get {
                return ResourceManager.GetString("Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить профиль.
        /// </summary>
        public static string FileDialog_SaveProfile {
            get {
                return ResourceManager.GetString("FileDialog_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершено.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фарм запущен....
        /// </summary>
        public static string FormMain_btnStart_Click_FarmBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фарм запущен с интервалом .
        /// </summary>
        public static string FormMain_btnStart_Click_FarmBeginWithInterval {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmBeginWithInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фарм завершен.
        /// </summary>
        public static string FormMain_btnStart_Click_FarmFinish {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропуск попытки фарма. Предыдущий цикл фарма еше не окончен..
        /// </summary>
        public static string FormMain_btnStart_Click_FarmSkip {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_FarmSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  циклов осталось).
        /// </summary>
        public static string FormMain_btnStart_Click_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м (.
        /// </summary>
        public static string FormMain_btnStart_Click_M {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        public static string FormMain_btnStart_Click_Stop {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется....
        /// </summary>
        public static string FormMain_btnStart_Click_TaskBegin {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_TaskBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт.
        /// </summary>
        public static string FormMain_btnStart_Click_Старт {
            get {
                return ResourceManager.GetString("FormMain_btnStart_Click_Старт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фарм.
        /// </summary>
        public static string FormMain_DoFarm_Farn {
            get {
                return ResourceManager.GetString("FormMain_DoFarm_Farn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string FormMain_Label_Status {
            get {
                return ResourceManager.GetString("FormMain_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осталось циклов.
        /// </summary>
        public static string FormMain_timer_Tick_LoopsLeft {
            get {
                return ResourceManager.GetString("FormMain_timer_Tick_LoopsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игр в Blacklist&apos;e.
        /// </summary>
        public static string GamesInBlacklist {
            get {
                return ResourceManager.GetString("GamesInBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурация.
        /// </summary>
        public static string GetBotInConfig_Config {
            get {
                return ResourceManager.GetString("GetBotInConfig_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не загружена. Файл не существует или сломан..
        /// </summary>
        public static string GetBotInConfig_NotLoaded {
            get {
                return ResourceManager.GetString("GetBotInConfig_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to угля.
        /// </summary>
        public static string GiveawayJoined_Coal {
            get {
                return ResourceManager.GetString("GiveawayJoined_Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подтверждено за.
        /// </summary>
        public static string GiveawayJoined_ConfirmedFor {
            get {
                return ResourceManager.GetString("GiveawayJoined_ConfirmedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие в.
        /// </summary>
        public static string GiveawayJoined_Join {
            get {
                return ResourceManager.GetString("GiveawayJoined_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string GiveawayJoined_Points {
            get {
                return ResourceManager.GetString("GiveawayJoined_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не подтверждено.
        /// </summary>
        public static string GiveawayNotJoined_NotConfirmed {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны состоять в группе.
        /// </summary>
        public static string GiveawayNotJoined_YouMustEnteredToGroup {
            get {
                return ResourceManager.GetString("GiveawayNotJoined_YouMustEnteredToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас есть выигрыш.
        /// </summary>
        public static string GiveawaysHaveWon {
            get {
                return ResourceManager.GetString("GiveawaysHaveWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас устаревшая версия Internet Explorer. Чтобы избежать проблем с работой программы, рекомендуется обновить. Перейти на сайт Microsoft для скачивания обновления?.
        /// </summary>
        public static string IECheck {
            get {
                return ResourceManager.GetString("IECheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используя программу, вы соглашаетесь с тем, что разработчик не несет ответственности за ваши аккаунты. Все действия инициируются пользователем и только пользователь ответственен за них..
        /// </summary>
        public static string Licens {
            get {
                return ResourceManager.GetString("Licens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На сайт.
        /// </summary>
        public static string LinkLabel_OnSite {
            get {
                return ResourceManager.GetString("LinkLabel_OnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль загружен.
        /// </summary>
        public static string LoadProfile_Load {
            get {
                return ResourceManager.GetString("LoadProfile_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка авторизации.
        /// </summary>
        public static string LoginFaild {
            get {
                return ResourceManager.GetString("LoginFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизован.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержать.
        /// </summary>
        public static string MainForm_Donate {
            get {
                return ResourceManager.GetString("MainForm_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление информации о.
        /// </summary>
        public static string MainForm_UpdateInfoAbout {
            get {
                return ResourceManager.GetString("MainForm_UpdateInfoAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку с ботом.
        /// </summary>
        public static string OpenBotFolder {
            get {
                return ResourceManager.GetString("OpenBotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contributors раздач на.
        /// </summary>
        public static string ParseLoadGiveaways__ContributorsIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways__ContributorsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено.
        /// </summary>
        public static string ParseLoadGiveaways_Found {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено груповых раздач.
        /// </summary>
        public static string ParseLoadGiveaways_FoundGiveAwaysInGroup {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено раздач в вишлисте.
        /// </summary>
        public static string ParseLoadGiveaways_FoundGiveAwaysInWishList {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundGiveAwaysInWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено подходящих раздач.
        /// </summary>
        public static string ParseLoadGiveaways_FoundMatchGiveaways {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FoundMatchGiveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бесплатных золотых раздач на.
        /// </summary>
        public static string ParseLoadGiveaways_FreeGoldenGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_FreeGoldenGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to групповых раздач на.
        /// </summary>
        public static string ParseLoadGiveaways_GroupGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_GroupGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to страницах.
        /// </summary>
        public static string ParseLoadGiveaways_Pages {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обычных раздач на.
        /// </summary>
        public static string ParseLoadGiveaways_RegularGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_RegularGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раздач из пеcочницы на.
        /// </summary>
        public static string ParseLoadGiveaways_SandboxGiveawaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_SandboxGiveawaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раздач из вишлиста на.
        /// </summary>
        public static string ParseLoadGiveaways_WishListGiveAwaysIn {
            get {
                return ResourceManager.GetString("ParseLoadGiveaways_WishListGiveAwaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Угля.
        /// </summary>
        public static string ParseProfile_Coal {
            get {
                return ResourceManager.GetString("ParseProfile_Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень.
        /// </summary>
        public static string ParseProfile_Level {
            get {
                return ResourceManager.GetString("ParseProfile_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка логина/сервера.
        /// </summary>
        public static string ParseProfile_LoginOrServerError {
            get {
                return ResourceManager.GetString("ParseProfile_LoginOrServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string ParseProfile_Points {
            get {
                return ResourceManager.GetString("ParseProfile_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка профиля.
        /// </summary>
        public static string ProfileLoading {
            get {
                return ResourceManager.GetString("ProfileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить куки браузера.
        /// </summary>
        public static string SetitngsForm_btnDeleteCookies {
            get {
                return ResourceManager.GetString("SetitngsForm_btnDeleteCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резерв угля:.
        /// </summary>
        public static string SettingForm_label2 {
            get {
                return ResourceManager.GetString("SettingForm_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string SettingForm_tbGMMaxValue {
            get {
                return ResourceManager.GetString("SettingForm_tbGMMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автозагрузка.
        /// </summary>
        public static string SettingsForm_cbAutorun {
            get {
                return ResourceManager.GetString("SettingsForm_cbAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещение о фарме.
        /// </summary>
        public static string SettingsForm_cbFarmTip {
            get {
                return ResourceManager.GetString("SettingsForm_cbFarmTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесплатные золотые раздачи.
        /// </summary>
        public static string SettingsForm_cbGMGolden {
            get {
                return ResourceManager.GetString("SettingsForm_cbGMGolden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без региональных ограничений.
        /// </summary>
        public static string SettingsForm_cbGMRegional {
            get {
                return ResourceManager.GetString("SettingsForm_cbGMRegional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычные раздачи.
        /// </summary>
        public static string SettingsForm_cbGMRegular {
            get {
                return ResourceManager.GetString("SettingsForm_cbGMRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сначала.
        /// </summary>
        public static string SettingsForm_cbSort {
            get {
                return ResourceManager.GetString("SettingsForm_cbSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включен.
        /// </summary>
        public static string SettingsForm_cbTimerEnable {
            get {
                return ResourceManager.GetString("SettingsForm_cbTimerEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не применять сортировку к вишлисту.
        /// </summary>
        public static string SettingsForm_cbWishlistSort {
            get {
                return ResourceManager.GetString("SettingsForm_cbWishlistSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещение о победах.
        /// </summary>
        public static string SettingsForm_cbWonTip {
            get {
                return ResourceManager.GetString("SettingsForm_cbWonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздачи из песочницы.
        /// </summary>
        public static string SettingsForm_chGMSandbox {
            get {
                return ResourceManager.GetString("SettingsForm_chGMSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие.
        /// </summary>
        public static string SettingsForm_Commun {
            get {
                return ResourceManager.GetString("SettingsForm_Commun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string SettingsForm_gbTimerSettings {
            get {
                return ResourceManager.GetString("SettingsForm_gbTimerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таймер.
        /// </summary>
        public static string SettingsForm_groupBox1 {
            get {
                return ResourceManager.GetString("SettingsForm_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал таймера не может равняться 0.
        /// </summary>
        public static string SettingsForm_IntervalNotZero {
            get {
                return ResourceManager.GetString("SettingsForm_IntervalNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная ставка:.
        /// </summary>
        public static string SettingsForm_label1 {
            get {
                return ResourceManager.GetString("SettingsForm_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал:.
        /// </summary>
        public static string SettingsForm_label5 {
            get {
                return ResourceManager.GetString("SettingsForm_label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.
        /// </summary>
        public static string SettingsForm_label6 {
            get {
                return ResourceManager.GetString("SettingsForm_label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шт.
        /// </summary>
        public static string SettingsForm_label7 {
            get {
                return ResourceManager.GetString("SettingsForm_label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Циклов: .
        /// </summary>
        public static string SettingsForm_label8 {
            get {
                return ResourceManager.GetString("SettingsForm_label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SettingsForm_tbGMReserv {
            get {
                return ResourceManager.GetString("SettingsForm_tbGMReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string SettingsForm_tbTimerInterval {
            get {
                return ResourceManager.GetString("SettingsForm_tbTimerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SettingsForm_tbTimerLoops {
            get {
                return ResourceManager.GetString("SettingsForm_tbTimerLoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт....
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не авторизован.
        /// </summary>
        public static string Status_NotLogined {
            get {
                return ResourceManager.GetString("Status_NotLogined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершено.
        /// </summary>
        public static string StatusBar_End {
            get {
                return ResourceManager.GetString("StatusBar_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string StatusBar_Login {
            get {
                return ResourceManager.GetString("StatusBar_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже состоите в этой группе.
        /// </summary>
        public static string SteamGroupAlreadyMember {
            get {
                return ResourceManager.GetString("SteamGroupAlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие в группе подтверждено.
        /// </summary>
        public static string SteamGroupJoined {
            get {
                return ResourceManager.GetString("SteamGroupJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие в группе НЕ подтверждено.
        /// </summary>
        public static string SteamGroupNotJoined {
            get {
                return ResourceManager.GetString("SteamGroupNotJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация....
        /// </summary>
        public static string TryLogin {
            get {
                return ResourceManager.GetString("TryLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актуальная версия.
        /// </summary>
        public static string Updater_CurrentVersion {
            get {
                return ResourceManager.GetString("Updater_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно обновление.
        /// </summary>
        public static string Updater_HaveUpdate {
            get {
                return ResourceManager.GetString("Updater_HaveUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление завершено. Перезапуск....
        /// </summary>
        public static string Updater_Update_UpdateDone {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При обновлении произошла ошибка.
        /// </summary>
        public static string Updater_Update_UpdateFailed {
            get {
                return ResourceManager.GetString("Updater_Update_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
